Puc2.Mvc/Controllers/ColetasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Puc2.Mvc.Context;
using Puc2.Mvc.Entidades;
using Puc2.Mvc.Atributos;


namespace Puc2.Mvc.Controllers
{
    [MinhaAutenticacao]
    public class ColetasController : Controller
    {
        private Puc2.RegraDeNegocio.Coleta _negocioColeta;

        //private MyDbContext db = new MyDbContext();
        public ColetasController()
        {
            _negocioColeta = new RegraDeNegocio.Coleta();
        }

        // GET: Coletas
        public ActionResult Index()
        {
            var model = _negocioColeta.Listar();

            return View(model);
        }

        // GET: Coletas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Modelo.ColetaView coleta = _negocioColeta.PorId(id);
            if (coleta == null)
                return Content("Coleta não encontrada");

            return View(coleta);
        }

        // GET: Coletas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Coletas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idPedidoColeta,EndereRetirada,EnderecoEntrega")] Modelo.ColetaView coleta)
        {
            if (ModelState.IsValid)
            {
                //                db.Coletas.Add(coleta);
                //                db.SaveChanges();

                int? id = _negocioColeta.Incluir(coleta);
                if (id == null)
                    return Content("Coleta não encontrada");

                return RedirectToAction("Index");
            }

            return View(coleta);
        }

        // GET: Coletas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Coleta coleta = db.Coletas.Find(id);
            Modelo.ColetaView coleta = _negocioColeta.PorId(id);
            if (coleta == null)
            {
                return HttpNotFound();
            }
            return View(coleta);
        }

        // POST: Coletas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idPedidoColeta,EndereRetirada,EnderecoEntrega")] Modelo.ColetaView coleta)
        {
            if (ModelState.IsValid)
            {
 
                _negocioColeta.Alterar(coleta);

                return RedirectToAction("Index");
            }
            return View(coleta);
        }

        // GET: Coletas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Coleta coleta = db.Coletas.Find(id);
            Modelo.ColetaView coleta = _negocioColeta.PorId(id);
            if (coleta == null)
            {
                return HttpNotFound();
            }
            return View(coleta);
        }

        // POST: Coletas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //Coleta coleta = db.Coletas.Find(id);
            //db.Coletas.Remove(coleta);
            //db.SaveChanges();

            Modelo.ColetaView coleta = _negocioColeta.PorId(id);
            _negocioColeta.Excluir(coleta);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _negocioColeta.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Puc2.Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Puc2.Mvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Puc2.Mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Puc2.Mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Puc2.Mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Trasnportes XPTO</h1>
    <p class="lead">Portal desenvolvído para validação do conceito arquitetural da proposta de um sistema de gestão de logística.</p>
    <p class="lead">Projeto arquitetural proposto pelo TCC do curso : Especialização em Arquitetura de Software Distribuído.</p>
    <p class="lead">Aluno: Marcelo Mangolin Zampereti.</p>
    <p><a href="https://www.linkedin.com/in/marcelo-mangolin-06623624" class="btn btn-primary btn-lg" target="_blank">Linkedin Marcelo &raquo;</a></p>
</div>


<div class="row">
    <div class="col-md-12">
        <h2>Conceitos arquiteturais defendidos neste projeto.</h2>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Acesso por multi-plataforma</h2>
        <p>
            Este conceito visa representar a solução adotada para visualização em diversos dispositivos com telas de tamanhos diversos.
            O portal deve se adequar as dimensões do dispositivo que o utiliza, ajustando tamanhos de fontes, posicionamento de informações
            de uma forma que fique legível e de fácil acesso em qualquer dispositivo.
        </p>
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Cadastro de Coleta", "Index", "Coletas")</li>
        </ul>
        <ul class="btn btn-default">
            <li>@Html.ActionLink("Cadastro de Coleta >>", "Index", "Coletas")</li>
        </ul>
    </div>
    <div class="col-md-4">
        <h2>Segurança no acesso ao portal</h2>
        <p>O portal prevê a utilização do Microsoft Identity fornecido pelo próprio Azure, garantindo estrutura mínima e robusta de controle de acesso.</p>
        <p>Todo acesso as páginas do portal somente será permitido após o devido cadastro e login efetuado.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Fácil evolução de aplicativo</h2>
        <p>O portal foi desenvolvido com a solução Microsoft C# usando frameworks de ultima geração, consolidados e de fácil conehcimento do mercado:</p>
        <p>-C#/VisualStudio, linguagem e IDE largamente conhecida pela comunidade de desenvolvedores.</p>
        <p>-MVC, framework que fornece separação de Visualização, Dados e Controle, de fácil adequação e evolução. </p>
        <p>-Angular, framework que fornece padronização de identidade visual, que premite rápida reconfiguração de parametros visual do portal.</p>
        <p>-SQLServe, banco de dados fortemente conhecido pela comunidade de desenvolvedores, com possibilidade de manutenção, cerscimento e migração.</p>
        <p>-Azure, ambiente de gestão e hopedagem na nuvem que garante o funcionamento, disponibilidade, flexibilidade, evolução e suporte 24x7 do aplicativo desenvolvído.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>